language: go

os: 
  - linux

go:
  - "1.10"

install:
  - make dependencies
  - make fmt
  - make lint
  - glyphcheck ./...
  - make dev
  - make vet

# script: make test

branches:
  only:
    - master
    - staging
